
services:

  mongodb:
    image: mongo:latest
    container_name: realestate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - realestate-network

  # API .NET Service
  api:
    container_name: realestate-api
    build:
      context: ./backend
      dockerfile: RealEstate.API/Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings:ConnectionString=mongodb://mongodb:27017
      - ASPNETCORE_URLS=http://+:80
    networks:
      - realestate-network

  frontend:
    container_name: realestate-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - realestate-network

volumes:
  mongo-data:
    driver: local

networks:
  realestate-network:
    driver: bridge
